# Compose file for monitoring the Alastria RedT Validators
services:
  signers:
    build: .
    restart: unless-stopped
    container_name: "signers"
    deploy:
      resources:
        limits:
          memory: 400M
    ports:
      - "8080:8080"
    volumes:
      - "../sqlblockchain:/root/sqlitedata"
    command: ["serve", "-u", "ws://172.31.44.212:22001"]

  caddy:
    image: caddy:2.5.1-alpine
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 400M
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/caddy/caddy_data:/data
      - $PWD/caddy/caddy_config:/config
